# kubectl apply -f infra/infra-study/drink/spring-config.yaml
# kubectl get configmap

apiVersion: v1
kind: ConfigMap

metadata:
  name: spring-config

data:
  db-host: mysql-service
  db-port: "3306"
  db-name: kub-practice
  my-account: woosong

